### ISSUE TITLE
REGARDING:- GET PROPERTY DOESN'T WORK WHEN USING "HTTP" SERVICES.

### ISSUE THREAD

**Issue by harshilravi** [DeborahK/Angular-GettingStarted#103] opened 2018-10-18 09:55 UTC
Hi DeborahK,

I have start learning Angular 4 with your Tutorial and also I am making same Application as you are used in Tutorial.
but right now I am stuck with little bit. Problem is that I am using "http" services in product.services.ts.
And I facing error regrading "get method".
Error message:-
"ERROR in C:/Users/Jatin/Desktop/angular 4/Angular-GettingStarted-master/APM-Start/src/app/products/product.service.ts (18,26): Property 'get' does not exist on type
'typeof HttpClient'."

It would be great you can help me ASAP.

Thanks
Harshil Thakkar

**Comment by DeborahK** [comment] 2018-10-18 10:11
I'm currently on vacation in New Zealand with no computer, so I may not help much.

The first thing to check is that you have added HttpClient module to the imports array in the app module.

If that doesn't help, try posting to the discussion board for the course. There are several there that can help.

**Comment by harshilravi** [comment] 2018-10-18 12:32
Thanks for Replying. 
I have done as per your suggestion this but still this happens. However I am trying and finding how to resolved it.  
Please find Attachment.

![image](https://user-images.githubusercontent.com/26621748/47154411-e37e5180-d2ff-11e8-89d4-e99e3a6a7413.png)

**Comment by bauca** [comment] 2018-10-18 13:03
Sorry to intrude in this thread but I think that you should take a look into  [this post within stackoverflow.](https://stackoverflow.com/questions/47369850/property-get-does-not-exist-on-type-httpclientmodule)
I think that you have the same problem as the person who created the post.

**Comment by harshilravi** [comment] 2018-10-23 10:06
still I am getting this error same. Let you correct me where I was  wrong?
hope so I will get solution ASAP. 
Please find Attachment.
![image](https://user-images.githubusercontent.com/26621748/47353152-3299fd00-d6d9-11e8-9b8a-6a060b7e6ec6.png)

**Comment by DeborahK** [comment] 2018-10-24 10:56
I'm still on holiday in New Zealand. I'll be back in the office on Monday.

**Comment by DeborahK** [comment] 2018-10-29 18:58
I am back and was able to look at your code more specifically. The issue is in your constructor. It should be this:

constructor(private http: HttpClient) { }

Notice that it is a colon and not an equal sign.

Let me know if that resolves your issue.

**Comment by DeborahK** [comment] 2018-10-30 18:31
Are you truly learning Angular 4? My course is for Angular *6*. The `providedIn` feature is an Angular 6 feature and is not available in Angular v4.

I'm closing this issue.

Please post future questions to the 'Discussion' tab on the Pluralsight page.

Thanks!

**Closed by DeborahK** 2018-10-30 18:31 UTC
